# Permalinks
permalink:           pretty

# Setup
title:               Erik Kristofer Anderson
tagline:             A Perfectly Adequate Blog
url:                 http://ekand.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Erik Kristofer Anderson
  url:               https://twitter.com/ekand_erik
  email:             erik.kristofer.anderson@gmail.com

# Custom vars
version:             0.1.0
github:
  repo:              https://github.com/ekand/ekand.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'

theme: jekyll-theme-minimal